### ISSUE TITLE
TTQueue is not fully implemented

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaCore#114]
The scheduler and a few other things also rely on this being properly implemented.  For example, to get calls 
pushed back into the main thread.

The primary issue is how the queue should be serviced.  On the Mac 
See 
http://developer.apple.com/documentation/CoreFoundation/Reference/CFRunLoopRef/Reference/reference.h
tml and http://developer.apple.com/documentation/CoreFoundation/Reference/CFRunLoopObserverRef/Reference/re
ference.html#//apple_ref/doc/c_ref/CFRunLoopObserverRef .  

A pseudo implementation might look like this:

CFRunLoopRef theLoop = CFRunLoopGetMain();
CFRunLoopObserverRef theLoopObserver= (create the observer with the callback, etc.);

CFRunLoopAddObserver (theLoop, theLoopObserver, kCFRunLoopCommonModes);

Still need to research what happens on Windows so that we can service the queue.

 see more on the original redmine issue http://redmine.jamoma.org/issues/126

**Comment by tap** [comment]
not happening in Jamoma1
