### ISSUE TITLE
Writing up Doxygen page on how to build a simple C++ audio graph with a bunch of DSP units.

### ISSUE THREAD

**Issue by lossius** [jamoma/JamomaCore#167]
Quoting a mail from Tim:

*You said "connecting a saw, to a lp filter in an audio graph and pulling blocks of samples on the audio side"...  That's wicked easy :-).*

*I was sure this would be in our DAFx paper ( http://jamoma.org/publications/attachments/jamoma-audiograph-DAFx.pdf ) but I just looked and we have Max, Pd, Ruby, etc. but no C++ example.  How in the world did we not include a C++ example???*

*I also didn't include C++ code in http://74objects.com/2010/02/03/designing-multicore/ -- huh???*

*So the best documentation right now is to use Plugtastic.  I don't know if Plugtastic even works in the current builds, but I think it should work in the last release (?).  If you try using the "My Plugtastic Adventure" and build an AudioUnit plug-in with it, then it should be possible to find the Xcode project it generated and look at the source code for that.  Sorry that I'm not able to try it right now for you!*

*That source code it generates will have an audio graph that gets pulled by the AudioUnit host.  It will also have parameter objects that get values pushed to them from the AudioUnit host which then further push on the rest of the graph(s).*

We should write up an example of how to do this as part of the Doxygen pages. I'm setting this as being urgent, as Jan schacher might also need it for a prototype SpatDIF implementation.

**Comment by tap** [comment]
This was discussed at the Jamoma workshop.  It's a bit onerous and work will proceed much more happily in Jamoma2.
