### ISSUE TITLE
TTSampleMatrix::fill() algorithms test & review

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaCore#19]
Found and corrected a few things today (phase of triangle, count start at zero).  Need to do a more thoroughly look at the code here.

At the very least, these algorithms could be optimized.  At most, a few of the algorithms may need corrections.  The kTTSym_triangleMod looks suspicious.

 see more on the original redmine issue http://redmine.jamoma.org/issues/1297

**Comment by nwolek** [comment]
Relevant code is found here: 
https://github.com/jamoma/JamomaCore/blob/master/DSP/library/source/TTSampleMatrix.cpp#L254

**Comment by nwolek** [comment]
Closing here and making a note for jamoma2.
