### ISSUE TITLE
TTData::setDecimalValue needs review

### ISSUE THREAD

**Issue by nwolek** [jamoma/JamomaCore#211]
There are several questions here that things may not be happening in the right order or be the most efficient method...

Why are we only clipping if we are ramping?
Why are we stopping the ramping after we set a new value?

Raised during code review 5 March Bergen

**Comment by lossius** [comment]
I am currently revamping this code to implement dataspace + ramping. In the process the sequence of most of this is altered somewhat. I'm very close now to having this fully working with decimals, and have also found some other issues along the way. I consider this a code review that is also responding to this issue. While it still might be possible to optimise the code, i believe it will end up with a fairly sane step of tasks involved in the processing.

As such I'm considering this issue to be closed.
