### ISSUE TITLE
doxygen: documenting macros properly

### ISSUE THREAD

**Issue by tap** [jamoma/JamomaCore#276]
We have macros and in some cases they even have doxygen comments :-) For example, TT_NO_DEPRECATION_WARNINGS in TTBase.h.

The documentation for this does not show up in Xcode's documentation pane though which leads me to believe that we need some magic.  Do you know what that magic is?

**Comment by nwolek** [comment]
Added section on adding Macros to Doxygen group here: 
https://github.com/jamoma/Jamoma/blob/dev/Doxygen/intro_chapters/C-StyleGuide.dox#L156

Part of resolving this issue on umbrella:
https://github.com/jamoma/Jamoma/issues/122

Does that also close this issue?

**Comment by nwolek** [comment]
This issue migrated from talking about macros to making the Doxygen comments display in Xcode. Since our work on jamoma2 seems to have positive results toward this goal, I am closing the issue here.
