### ISSUE TITLE
Port gverb~ to JamomaDSP

### ISSUE THREAD

**Issue by tap** [jamoma/JamomaCore#279]
This one will require some help from @nwolek since he is the one currently in possession of the source code :-)

First iteration can be the algorithm as it exists: stereo (and maybe mono?).

A second iteration will involve some research into ways that the algorithm can expand to additional channel configurations.

This topic was first discussed by @tap and @nwolek in the Augustin lobby during the 2014 workshop at BEK.

**Comment by nwolek** [comment]
Now ported for Max 7 here: https://github.com/nwolek/LowkeyNW/tree/master/source/nw.gverb~

Are we still interested in porting for Jamoma too?

**Comment by tap** [comment]
Is that a serious question?  Of course!

Tim

**Comment by nwolek** [comment]
OK, adding to my list for next week!

**Comment by lossius** [comment]
While at it we should port tap.verb~ as well.

**Comment by nwolek** [comment]
The tap.verb~ source is here: 
https://github.com/tap/TapTools/tree/master/source/tap.verb~

**Comment by nwolek** [comment]
moved to jamoma/jamoma2#41
