### ISSUE TITLE
Why are tests using TTObjectBaseInstantiate not generating deprecation warnings?

### ISSUE THREAD

**Issue by nwolek** [jamoma/JamomaCore#295]
On May 7, 2014, at 4:31 PM, Trond Lossius <trond.lossius@bek.no> wrote:
@nwolek : "It might be that the unit test for TTMutesolo introduce deprecations. Could you please help me look into this?"

I see some use of TTObjectBaseInstantiate in the following two tests, which should generate deprecation warnings: 

https://github.com/jamoma/JamomaCore/blob/merge/api_and_api-cleanup/DSP/extensions/EffectsLib/tests/TTMuteSolo.test.cpp

https://github.com/jamoma/JamomaCore/blob/merge/api_and_api-cleanup/DSP/extensions/EffectsLib/tests/TTThru.test.cpp

I can refactor the code, but to me there is a large issue of not seeing any warnings. Any ideas why @tap or @lossius?

**Comment by tap** [comment]
the whole build system and test execution system has changed now, so this is no longer relevant.
