### ISSUE TITLE
TTElement::round() and truncate() methods are inconsistent

### ISSUE THREAD

**Issue by nwolek** [jamoma/JamomaCore#300]
@tap - please advise on whether this is intentional or a copy/paste error. Once I get your input, I am happy to refactor the code so just assign it back to me. This should probably be a hotfix.

1) round() method is attempting to round integers, which is not possible:
https://github.com/jamoma/JamomaCore/blob/issue/165/Foundation/library/includes/TTElement.h#L1049

2) truncate() method is changing the return type which @losius and I agree should not be the case:
https://github.com/jamoma/JamomaCore/blob/dev/Foundation/library/includes/TTElement.h#L1045

Note that the trunc() and round() methods in C++ leave type alone. Should we follow this convention?
http://www.cplusplus.com/reference/cmath/round/
http://www.cplusplus.com/reference/cmath/trunc/

**Comment by tap** [comment]
Not making potentially hard-to-track bug-inducing changes like this for Jamoma1.  In Jamoma2, if we need these types of operations, we should do them as discussed -- returning a copy rather than using a side-effect.
