### ISSUE TITLE
TTList : allow to register as none pointer members

### ISSUE THREAD

**Issue by theod** [jamoma/JamomaCore#305]
For example it is not possible to change a TTListPtr member into a TTList member of a TTObject class because the only possibility is to register it using addAttribute(Name, kTypePointer)) and then it is not possible to get it.

In the example below :

	TTListPtr	lines;
	TTValue	v;
	
	mScript.get(kTTSym_lines, v);
	lines = TTListPtr((TTPtr)v[0]);
	
The lines variable is not usable (bad size, no way to iterate on it, …).

A proposition could be to allow something like addAttribute(Name, kTypeReference))

**Comment by tap** [comment]
Hi @theod -- assigning back to you if you wish to do something with this for Jamoma1.  Long term (Jamoma2) we should not have this problem.

**Comment by theod** [comment]
no it's ok. I don't feel this to be very important if we plan to redesign the framework.
