### ISSUE TITLE
Optimize TTData ramping

### ISSUE THREAD

**Issue by theod** [jamoma/JamomaCore#313]
I noticed there is useless cpu consuming because we stop the Ramp unit even if there is no ramping.
As there is a RampStatus flag I guess we could optimize this to save more cpu.

**Comment by lossius** [comment]
@theod : Once I have pushed the changes to implement dataspace + ramping, maybe you can check again to see if this is still an issue?

**Comment by theod** [comment]
On feature/325-dataspace-ramp branch, for decimal type it seems you test the ramp status flag before to stop the ramp so I would say ok ! thanks !

I keep the issue opened until you do the same for integer and array type.

**Comment by lossius** [comment]
They all share the same method now, so I'm closing this issue,
