### ISSUE TITLE
Ambiguous conversion for functional-style cast from 'const value_type' (aka 'const TTElement') to 'TTDictionary'

### ISSUE THREAD

**Issue by theod** [jamoma/JamomaCore#319]
The following code doesn't compile : 

   TTDictionary state;
   object.get("state", state);

would it be possible to allow this @tap ?

**Comment by tap** [comment]
My current thinking is that we should handle this by using std::shared_ptr in TTValue.  While this would add to the size of TTElement, it would solve many many problems.

**Comment by tap** [comment]
Can we close this one @theod ?

**Comment by theod** [comment]
ok !
