### ISSUE TITLE
CMake failed to configure with export error

### ISSUE THREAD

**Issue by avilleret** [jamoma/JamomaCore#324]
on the feature/cmake branch, I can't configure the build system anymore due to export error.
Here is a complete log : https://gist.github.com/avilleret/13603cb6785524c184f0
Also, commenting the lines 41-43 of https://github.com/jamoma/JamomaCore/blob/feature/cmake/Shared/CMake/JamomaUtilFunctions.cmake#L41-L43 avoid the issue and I can build Jamoma without exporting it's configuration.

~~~~
$ cmake --version 
cmake version 2.8.12.2
~~~~

**Comment by jcelerier** [comment]
CMake required version was updated to 3.0.
