### ISSUE TITLE
TTData: If mType is "boolean", mValue and mValueDefault should be set to 0 at initialisation

### ISSUE THREAD

**Issue by lossius** [jamoma/JamomaCore#326]
This issue came up while porting integration tests for j.parameter in the Max implementation. In the tests for default attribute values of j.parameter with type = boolean, the default value of the "value" and "default" attributes is "bang" rather than "0". It makes no sense that a boolean parameter has the vale "bang", "0" would be much more appropriate (as is the case e.g. for a newly created Toggle object in Max).

When this issue is fixed, we also need to update the integration test accordingly in Max before closing it.

**Comment by theod** [comment]
As I read the integration test, it seems to be the same problem for decimal and integer type also isn't it ?

**Comment by lossius** [comment]
Yes, that's correct.

**Comment by lossius** [comment]
And when this has been fixed, the integration tests should be updated to reflect the new behaviour.

**Comment by theod** [comment]
do we want a value to be outputted from the j.parameter ?

**Comment by theod** [comment]
I have made a fix on feature/325... branch.

**Comment by lossius** [comment]
Yes, this now seems to work. I've uådated integration tests accordingly. I noticed another issue in the process, but I've mailed you at the devel list regarding this.

Thanks!
