### ISSUE TITLE
TTData with type decimal: If default is set as int, it is passed out as int rather than decimal

### ISSUE THREAD

**Issue by lossius** [jamoma/JamomaCore#329]
The following Max patch illustrates the problem

<pre><code>
----------begin_max5_patcher----------
424.3ocsTErSCCCC8b6WQTNWlZ51nLNw+.GQHTZiGKSsIUINvPH92o0okMXv
XbfKsxu3Z+dO6lWSS3U1cfmytlcGKI40zjDBZ.HYLNg2J2U2H8TZ7ZaaKXPd
V7LD1gD9sargFEyAXvYXR15FqDyXFKxjFld+WXBsZSCfT4DifUgppF3PjNIV
uQad7AGTiQBJJKmkmwJDKGdIVUPQKlkyteessAbp34inZEwPa01KJmXgGeI1
ONe.3szzgGYmoIzBdu7Q3HSP7shr3DRJ+pCjzxbJn3GUj3XEsbpkwzvW5fXo
47OJx+iXUvZYnA6IU+3Ui+YoOeEMFEjCTt5uK84+6R2.O22niT91YcRmrEPv
wVasraFZMSA05VYyI2yOgOrLtUWt3WLhhiMBwOaDY+tYPGyazludQ.Q1A7O6
PdavUO0fw1y1yVE3QsQhZq4fb5WSYhOxYiVo.yg+ipzdY+M.jlx+1I04xl4m
Aa9LiOe1DsJYW2SfyOVRhH8qMastgvxLJTahgTE4N3I8T9zp.W552Cv9kffK
NQ1c4Bd7SsJvYBZJ2zgN+V56ByfSUC
-----------end_max5_patcher-----------
</code></pre>

In the Max implementation, one of the assertions in the integration test

    disabled_integration_tests/tests_with_problems/fails/Modular/j.parameter/type_decimal/messages/j.parameter_type_decimal_messages.maxtest.maxpat  

fails for this reason. Once this issue has been fixed , that test should be moved to

    Jamoma/patchers/integrationTests/Modular/j.parameter/type_decimal/messages/

before this issue is closed.

**Comment by lossius** [comment]
This happens at the dev branch as well as the feature/325... branch.

**Comment by theod** [comment]
I have made a fix on feature/325... branch.

**Comment by lossius** [comment]
This has now been resolved, and help patch has been moved to its proper location.
