### ISSUE TITLE
TTData type decimal: First value is not output if it's 0. (the default value)

### ISSUE THREAD

**Issue by lossius** [jamoma/JamomaCore#330]
The following Max patch illustrates the problem

<pre><code>
----------begin_max5_patcher----------
637.3ocyV0zaaCCC8ryuBAcZCHMUxwIttmJvNueACCCJ1LIp0VxPRNIEE8+9
jnr2RWSV5WYXWrknoIeO9nn8CiRnKz6.KkbM4ajjjGFkjflBFR52mPaD6JqE
VzMZotoATN533ybvNGZ+Kqgx6H5Nm2AfHUjuJ1Q1JUU5sC9p5ZjpZvgAh2ab
wpRcs1Dg.aRQ5rrhw9ESmmkyliqx37bbEi78g2pawhZX+3zJbkqkpU+v.ktX
zRKJlvFSRYwayRwaY6EFOh7Hd.RrdqxJjQ5E2dAOa.7sFv54svI0p8xwTFFU
tOUyPH9TbZc2GgIkFL73nQgKieu05ZouV6VKsDgkrTZrtvN0JhXoCLDcKnB6
bqABVWtt2oMh5Nf7I1jO6kl5ZxBfzHsVuuSFRRsTAk5NEloz+px8Jzf4yCkm
dIXZ9qRBldBIHsXNlho+eq.RWrluUat6MTrO6GS3b9aWiRoeHk6FvZEqfmUt
uHiMwiPFiXDMsgEGblR5wIIO+pHI64ZbVP5QII+.j7WIM5m69VHFbJ8Cpc6X
7+cy9YYA9liW4L9qm7Emctqfs9D8Lp2Zj+972AOZbb9lxwICSyNAeOPG8Uzy
IotcRqvqkPXTwRslbSndRpfRYinlbiAZAmLLlyd4RYcvKl2pW7urxH23GZK1
8FKI7bV73cwIpIoG3.vw6AFe59.7w3Du+3+MPvFr+z5nU2YJGRPeKH42nsBr
NoB+Vvd9vehOqkUUfZeEtRZE9IhHmXGTOeong+BPyU+6PC6LVbhJmnscCXr8
gDQhuW+132jxGiakp3VLhTCrQN3O1YREFeaoy2S1YhMH6lG+AKZitBLpNI56
nPlebzOAqFferB
-----------end_max5_patcher-----------
</code></pre>

**Comment by lossius** [comment]
A number of integration tests in Max for j.parameter fails because of this issue. Once it is fixed, all integration tests that are currently located in 

    disabled_integration_tests/tests_with_problems/fails/Modular/j.parameter/type_decimal/

should be checked. If all assertions of a test pass, the test should be moved to the appropriate subfolder of

    Jamoma/patchers/integrationTests/Modular/j.parameter/type_decimal/

**Comment by jln-** [comment]
On which branch ? It seems ok here with a build on dev from yesterday

**Comment by lossius** [comment]
Yes, this works on the dev branch but is broken on the feature/325-... branch, so I'll assign to myself, as this has been broken in the dataspace + ramp integration process for type decimal.

**Comment by lossius** [comment]
This is fixed now.
