### ISSUE TITLE
TTRegex: Switch to std::regex and eliminate Boost dependency

### ISSUE THREAD

**Issue by tap** [jamoma/JamomaCore#352]
The crufty old Boost version needs to go.  

When we tried this a couple of years ago we ran into crashes and problems, in part because Boost was maybe using Perl Regex instead of ECMA Regex or something like that?  @theod may remember more details.  Unfortunately, I don't think we have any unit tests for this code so it will likely be more painful to change than it needs to be...

Regardless, we still want to get rid of the unnecessary dependency on now-obsolete and non-standard code.

**Comment by theod** [comment]
I've added a test class for this. I'll try to change for std::reggae soon as possible

**Comment by tap** [comment]
That's great!  Looking forward to using standard C++!

**Comment by theod** [comment]
I've commenting out the BOOST_REGEX defines in Foundation.yml.
all test pass and nothing crash so I would say it's ok

**Comment by theod** [comment]
but I still don't have eliminate the boost stuff from the repo.

**Comment by theod** [comment]
but it seems that in TTPath.cpp there is still a use of boost that can't be removed.

**Comment by jcelerier** [comment]
`grep "TTPath" **/*.{hpp,cpp}` shows that TTPath is used nowhere, so I think it is safe to delete (and remove boost by the way - hurrah for build times!).

**Comment by tap** [comment]
Yes, TTPath was previously only used by the extension loader.  Yay!

Tim

**Comment by jcelerier** [comment]
@nwolek : some tests shall still be run but the tests in TTNodeLib.test.cpp for this are passing, so maybe this issue can be closed up too :)

**Comment by nwolek** [comment]
Closing. Thanks @jcelerier!
