### ISSUE TITLE
Where are *-jamoma.a lib on Mac OS X ?

### ISSUE THREAD

**Issue by avilleret** [jamoma/JamomaCore#358]
I'm trying to build JamomaCore (dev) on Mac OS X with CMake today and I experienced this issue : 
https://gist.github.com/avilleret/6f02c4d3b97270e80491

It seems that SoundFileLib depends on SndFile.
And according to https://github.com/jamoma/JamomaCore/blob/dev/Shared/CMake/modules/FindSndfile.cmake, there should be a `DSP/extensions/SoundfileLib/libsndfile` folder.
Which is not the case on the `dev` branch but there is one on `feature/cmake` branch : https://github.com/jamoma/JamomaCore/tree/feature/cmake/DSP/extensions/SoundfileLib/libsndfile
Did I miss something ?

**Comment by jcelerier** [comment]
?? This folder is here on the dev branch too :
https://github.com/jamoma/JamomaCore/tree/dev/DSP/extensions/SoundfileLib/libsndfile/lib

I'll try to see about this bug and my other assignments by the end of the
week (I have a poster to finish before).



-------
Jean-Michaël Celerier
http://www.jcelerier.name

**Comment by avilleret** [comment]
I think there is a typo, according to https://github.com/jamoma/JamomaCore/blob/dev/Shared/CMake/modules/FindSndfile.cmake#L79 it should be `SNDFILE_LIBRARY`rather than `SNDFILE_LIBRARIES`

but build still fails with something similar to https://github.com/jamoma/JamomaPureData/issues/2

see https://gist.github.com/avilleret/c11018e3989d5e83191b

but with that patch, build still fails with undefined
