### ISSUE TITLE
Build error on dev in modular

### ISSUE THREAD

**Issue by jcelerier** [jamoma/JamomaCore#359]
Got a build error while trying to build, I'd dare not change something in fear of breaking something else in return ?

    Modular/library/source/TTOpmlHandler.cpp:127:50: error: use of undeclared identifier 'none'
                            aTTObject.send("WriteAsOpml", TTObject(this), none);
                                                                          ^
    Modular/library/source/TTOpmlHandler.cpp:153:55: error: use of undeclared identifier 'none'
            return aTTObject.send("WriteAsOpml", TTObject(this), none);
                                                                 ^
    Modular/library/source/TTOpmlHandler.cpp:161:21: error: use of undeclared identifier 'none'
            return Write(args, none);
                               ^
    Modular/library/source/TTOpmlHandler.cpp:218:53: error: use of undeclared identifier 'none'
                                            aTTObject.send("ReadFromOpml", TTObject(this), none);
                                                                                           ^
    Modular/library/source/TTOpmlHandler.cpp:241:56: error: use of undeclared identifier 'none'
            return aTTObject.send("ReadFromOpml", TTObject(this), none);
                                                                  ^
    Modular/library/source/TTOpmlHandler.cpp:249:20: error: use of undeclared identifier 'none'
            return Read(args, none);

**Comment by jcelerier** [comment]
Okay, it seems that this file isn't actually being built - should it still be in the repo ?

**Comment by tap** [comment]
@theod should know the answer.  If it is not used anymore, the more we can delete the better :-)

**Comment by theod** [comment]
I've just removed those useless files

**Comment by tap** [comment]
Merci!  

Just a note too about commits -- if you write " see #359 " or similar in your commit message then it will automatically link to the issue number, which is quite useful...  Thanks again!

**Comment by theod** [comment]
sure ! this trick often comes to my mind after pressing the Enter key ;-)
