### ISSUE TITLE
Build fails on dev branch

### ISSUE THREAD

**Issue by avilleret** [jamoma/JamomaCore#361]
here is the make output : https://gist.github.com/avilleret/a1b70a5aa2fa29c3f95d

This happens on a fresh clone on a fresh Ubuntu 14.04 installation.
It's strange since I can build it from dev branch on my laptop.

**Comment by jcelerier** [comment]
MMhh, I haven't got the time to check but I guess it's because this code requires at least gcc-4.9.
Could you try replacing the `{""};` and `{".ttso"};` by `= "";` and `= ".ttso";` ?

**Comment by avilleret** [comment]
thanks it works

indeed I'm using gcc 4.8.2 on Ubuntu 14.04
