### ISSUE TITLE
TTData: If ramp/drive is changed on the fly, previous ramp drive is not disposed of correctly

### ISSUE THREAD

**Issue by lossius** [jamoma/JamomaCore#362]
TTData does not seem to free the ramper properly when ramp drive is changed on the fly. Steps to reproduce:

1. With MaxImplementation on dev branch, open help file for j.parameter
2. Go to Ramp/ease pane
3. While in the middle of a ramping, change the ramp/drive to none.

This leads to the following crash, that seems to suggest that the previous ramp still has ticks scheduled even after it was supposed to be disposed of.

https://gist.github.com/lossius/d891de3ce72b17331653

**Comment by theod** [comment]
this is fixed now
