### ISSUE TITLE
TTDataspace: Is the speed dataspace assumed to be able to convert to and from fps?

### ISSUE THREAD

**Issue by lossius** [jamoma/JamomaCore#363]
In the speed dataspace we have the following units:

fps, kn, m/s, km/h, kmph, ft/s, mi/h, mph

I can't for the best of me understand what fps has to do here. My guess would be that this dataspace was made by copying and renaming the files of another dataspace, and then the fps unit has been left in by accident.

**Comment by lossius** [comment]
It turns out that fps is a bit of an ambiguous term here. Viewing the code in SpeedDatascape.cpp line 196 it is clear that "fps" is intended to mean "foot per second" here, not "frames per second". As I'm not from the US and not used to imperial units, I'm missing out on this and instead interpretes it as frames per second.

Do we want to use fps for both of these, or should we rather restrict ourselves to "ft/s" in the speed dataspace?

Assigning to @tap to get his opinion on this.

**Comment by tap** [comment]
agree that "fps" means frames per second and we can use "ft/s" if indeed that unit is useful to anyone at all.
