### ISSUE TITLE
regex_error at initialization

### ISSUE THREAD

**Issue by avilleret** [jamoma/JamomaCore#371]
When loading Jamoma on Raspberry Pi 2 (armv7) I got those errors :

~~~~
regex_error caught: The code was error_brack with expression "([-\w]+):/"
regex_error caught: regex_error caught: The code was error_brack with expression "[.]"
~~~~

they come from here : https://github.com/jamoma/JamomaCore/blob/feature/enable-Pd-build/Foundation/library/source/TTRegex.cpp#L41

So it seems that `mExpression = new TTExpression(anExpression, regex_constants::extended);` throw an exception.

This happens on a fresh native build of JamomaPuredata on Raspberry Pi 2.

Any hint on how to fix that ?

**Comment by tap** [comment]
What compiler are you using?

**Comment by avilleret** [comment]
gcc 4.8.2 for native compilation 
and arm-linux-gnueabihf-gcc 4.9.2 for cross-compilation

**Comment by avilleret** [comment]
gcc 4.9.2 works fine for native compilation on Linux x86_64

**Comment by avilleret** [comment]
I got the same on Jessie (previous was on Wheezy) with a native build with GCC 4.9.2.

**Comment by avilleret** [comment]
does anyone have an idea how to solve this ?
or at least what it means and what are the consequences ?

**Comment by avilleret** [comment]
this error disappeared on Raspberry Pi
maybe with a system update
so I close the issue
