### ISSUE TITLE
need to define LD_LIBRARY_PATH to run demo app

### ISSUE THREAD

**Issue by avilleret** [jamoma/JamomaCore#385]
I have to call : `LD_LIBRARY_PATH=/usr/local/jamoma/lib/ ./DemoApp`
to run the demo app
it should find the Jamoma lib itself (maybe with RPATH or kind of)

**Comment by laugre** [comment]
I added it to cmake file. You can specify DemoApp executable destination as cmake argument 
`cmake -DJAMOMA_MODULAR_BUILD_DEMOAPP:Bool=True -DMODULAR_DEMOAPP_INSTALL_FOLDER="..."`

It works on mac, and need to be tested on other platforms.

**Comment by avilleret** [comment]
I don't need anymore to define LD_LIBRARY_PATH to run demo app so I'm closing this issue
but there is an issue with the extension path, please see my comment : https://github.com/jamoma/JamomaCore/commit/7885bc4385613b280f9485d2f59d7815a4234924
