### ISSUE TITLE
make TTAudioObject.cpp more DRY

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaCore#57]
there are a lot of unit conversion methods within TTAudioObject.cpp.
Since we have our dataspace code for unit conversions, we should not repeat ourselves here and make this file more DRY. 

 see more on the original redmine issue http://redmine.jamoma.org/issues/786

**Comment by tap** [comment]
This is invalid.  The versions in TTAudioObject are there for high performance inlining.  The versions in the dataspace for maximum flexibility and configurability, thus serving an entirely different purpose -- and requiring that the two be written differently.
