### ISSUE TITLE
alternative clipmodes (wrap/fold) are not working in 0.6

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaCore#59]
Théo said that these functions are not implemented in TTValue

I'm assigning to Nils, as he's their daddy, but maybe Tim is the man of the situation ?

 see more on the original redmine issue http://redmine.jamoma.org/issues/764

**Comment by lossius** [comment]
A number of assertions in the Max implementation integration test

    disabled_integration_tests/tests_with_problems/fails/Modular/j.parameter/type_decimal/ramp/j_parameter_type_decimal_ramp_and_clipmode.maxpat

currently fails because of this issue. Once this issue has been resolved and all assertions pass, the integration test should be moved to

    Jamoma/patchers/integrationTests/Modular/j.parameter/type_decimal/ramp/
