### ISSUE TITLE
TTFile

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaCore#68]
A class to wrap fopen() and similar for reading/writing files, text or binary, and serving as a baseclass for more specialized file wrappers (like Matlab5 file i/o or audio file i/o).

Look to Ruby's classes for file i/o for inspiration.

How does this class interact with the TTPath class?  Should iron that out when creating this.

 see more on the original redmine issue http://redmine.jamoma.org/issues/722

**Comment by tap** [comment]
Not happening in Jamoma1, maybe Jamoma2
