### ISSUE TITLE
audio control of parameters

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaCore#75]
Should happen at the Audio Graph level I guess?  That way the solution is available in Ruby, Max, AU, etc.

How can we do this?

Nils suggested that a slide~ like approach be applied to all parameters, but I think we can do this on an ad hoc basis if we can just control any parameter with a signal.

Contradicting myself: in order for the parameter changes to be in lock-step with the audio itself then we would have to do this as a part of the process message -- which implies that some of this is actually infrastructure required at the DSP level.

 see more on the original redmine issue http://redmine.jamoma.org/issues/613

**Comment by tap** [comment]
moving to Jamoma2
